### ISSUE TITLE
Omitting title front frontmatter and having an H1 maps the H1 to title

### ISSUE THREAD

**Issue by WestonThayer** [sparkartgroup/gulp-markdown-to-json#11]
And it removes the H1 from the output. This creates a very confusing experience. I'd suggest either getting rid of it, or putting it behind an option that's off by default.

**Comment by pushred** [comment]
Agreed! I'm not sure why I've got something against H1's but I've made this behavior opt-in for the 1.0 update. The reason these were extracted originally was for situations where a document title might be displayed outside of the content area, in a header or navigation menu for example.
