### ISSUE TITLE
Consolidated output somtimes in wrong order

### ISSUE THREAD

**Issue by tomtick** [sparkartgroup/gulp-markdown-to-json#16]
I'm using the Consolidated Output method using `.pipe(gutil.buffer())` prior to converting the markdown to JSON but the data in the JSON is often out of order based on the file system.

For example, I have `button` and `font` directories, each with a markdown file `button.md` and `font.md` but in the JSON sometimes`font` appears before `button`. 

Any idea on how to fix? Not sure if it's a `gutil` issue or something with the conversion.

**Comment by pushred** [comment]
Is this using 1.0? I'm now processing everything asynchronously so this is probably a side effect.. There is a sort applied to the consolidated output but it must not be working anymore. Will have a look this evening, thanks for reporting!

**Comment by tomtick** [comment]
Thanks. Yes, using 1.0.0.

**Comment by pushred** [comment]
Think I found the issue, please give 1.0.1 a shot. If the output is still not as expected would you be able to share your source files by chance?

**Comment by tomtick** [comment]
Yes, it appears you've fixed it. Tested a number of times and so far the order is as expected. Thank you very much for looking into this so quickly!

**Comment by pushred** [comment]
Awesome! Glad I've been able to improve my responsiveness since the last issue you opened =)
