### ISSUE TITLE
The order of the consolidated output [Question]

### ISSUE THREAD

**Issue by levsthings** [sparkartgroup/gulp-markdown-to-json#18]
When combining bunch of Markdown files into a single JSON file, do we have any control over the order of objects? It appears that Markdown files are being added in an alphabetical order of their respective filename.

I'm using the task below: 

```
gulp.task('indexContent', () => {
  gulp.src('./content/**/*.md')
    .pipe(gutil.buffer())
    .pipe(markdownToJSON(marked, 'content/json/index.json'))
    .pipe(gulp.dest('.'))
});

```

**Comment by pushred** [comment]
Sorting is handled by the [sort-object][sort-object] module, this is applied after all async processing has completed. That module does provide a couple hooks to write custom sort functions, would that be a good solution for your needs? I could expose access in the plugin's options.

[sort-object]: https://github.com/doowb/sort-object

**Comment by pushred** [comment]
Another options that's perhaps better: the [gulp-json-sort](https://www.npmjs.com/package/gulp-json-sort/) plugin provides a similar sort function

**Comment by levsthings** [comment]
Thank you for the suggestions, gulp-json-sort does the trick!

**Comment by pushred** [comment]
Great! I'll add a note about it in the readme on the next update
