### ISSUE TITLE
"use strict" missed from 1.0.2 version published on npm

### ISSUE THREAD

**Issue by hgarcia** [sparkartgroup/gulp-markdown-to-json#20]
Hi:

Thanks for this package. We noticed that you pushed 1.0.2 today to npm the code at npm is missing the "use strict"; for /lib/plugin.js"

I noticed you pushed that code to github, but it looks like the version published on npm doesn't have that change.

Thanks again.

**Comment by pushred** [comment]
Sorry about that! I just published 1.0.3 with this update, thanks for letting me know someone is indeed using this plugin with node 4.x., will make sure changes pass CI for the next release.
